\chapter{HMM Model Applied to VPIN}

#Calculating the Likelihood

Now that the mathematical foundations of the HMM have been laid down, we are ready to extend the model for the problem that this paper is examining. As explained in the introduction, the data we are attempting to fit an HMM with is the number of buy and sell orders per volume bucket. That is, for each volume bucket $t$ we will have a bivariate observable trading process $\{X_t \equiv (B_t, S_t): t = 1,2, \dots T \}$. $B_t$ and $S_t$ are defined as the buyer and seller-initiated orders. We can further define the unobserved hidden state stochastic process $\{C_t \equiv (C_{b;t}, C_{s;t}) : t = 1,2, \dots T\}$.

The probability of observing $b_t$ buy orders and $s_t$ sell orders is driven by the fact that they arrive according to independent Poisson process, and as such, conditional on the state at a particular volume bucket $t$ is $(i, j)$ we can state:

\begin{align}
 \begin{aligned}\label{eq:bivarPois}
 p_{i,j}(X) &= Pr(X_t = x | C_{b;t} = i, C_{s;t} = j) \\
            &= p_i(b_t) p_j(s_t) \\ 
            &= e^{- \lambda_{b;i}} \frac{(\lambda_{b;i})^{b_t}}{b_t !} \times e^{- \lambda_{s;j}} \frac{(\lambda_{s;j})^{s_t}}{s_t !} \\ 
  \end{aligned}
\end{align}

This implies that any state $(i, j)$ that the market is in for the duration of the volume bucket is represented by a pair of distribution parameters $\lambda_{b;i}$ and $\lambda_{s;j}$. 

The $mn \times mn$ diagonal matrix of conditional probabilities ${P}(x)$ is defined as:
$$\mathbf{P}(x) = \begin{pmatrix}
                   p_1(b_t) p_1(s_t) &        & 0 \\
                                     & \ddots &   \\
                   0                 &        & p_m(b_t) p_n(s_t)
                  \end{pmatrix}$$

We can now extend the unconditional state distribution defined in \eqref{eq:stateDist} as follows:

\begin{equation}\nonumber
  u_{i,j}(t) = Pr(C_{b;t} = i, C_{s;t} = j), t = 1,\dots,T
\end{equation}

Or in matrix format:

\begin{equation}\nonumber
  u_{i,j}(t) = \begin{pmatrix}
                     u_{1,1}(t),\dots,u_{1,n}(t), \dots u_{m,1}(t), \dots u_{m,n}(t)
               \end{pmatrix}
\end{equation}

The marginal distribution of $X$ extends logically from \eqref{eq:marginalNonStatWorking}, showing the unconditional probability of observing $x_t = (b_t, s_t)$ within volume bucket $t$:

\begin{align}
 \begin{aligned}\nonumber
    Pr(X_t = x) &= \sum_{i=1}^m \sum_{j=1}^n Pr(C_{b;t} = i, C_{s;t} = j) Pr(X_t = x | C_{b;t} = i, C_{s;t} = j) \\
                &= \sum_{i=1}^m \sum_{j=1}^n u_{i,j}(t) p_{i,j}(x) \\
                &= \begin{pmatrix}
                     u_{1,1}(t),\dots,u_{1,n}(t), \dots u_{m,1}(t), \dots u_{m,n}(t)
                   \end{pmatrix}
                   \begin{pmatrix}
                     p_1(b_t) p_1(s_t) &        & 0 \\
                                       & \ddots &   \\
                     0                 &        & p_m(b_t) p_n(s_t)
                   \end{pmatrix}
                   \begin{pmatrix}
                     1 \\
                     \vdots \\
                     1 
                   \end{pmatrix} \\
                &= \mathbf{u}(t) \mathbf{P}(x) \mathbf{1'}
 \end{aligned}
\end{align}

The transition probability matrix $\boldsymbol{\Gamma}(t)$ which is the $mn \times mn$ matrix of transition probabilities at state $t$ is defined as:

$$\boldsymbol{\Gamma}(1) = 
\begin{pmatrix}
  \gamma_{1,1;1,1}   \qquad \gamma_{1,1;1,2}   & \cdots & \gamma_{1,1;m,n-1}   \qquad \gamma_{1,1;m,n}\\
  \gamma_{1,2;1,1}   \qquad \gamma_{1,2;1,2}   &        & \gamma_{1,2;m,n-1}   \qquad \gamma_{1,2;m,n}\\
  \vdots                                       & \ddots & \vdots  \\
  \gamma_{m,n-1;1,1} \qquad \gamma_{m,n-1;1,2} &        & \gamma_{m,n-1;m,n-1} \qquad \gamma_{m,n-1;m,n}\\
  \gamma_{m,n;1,1}   \qquad \gamma_{m,n;1,2}   & \cdots & \gamma_{m,n;m,n-1}   \qquad \gamma_{m,n;m,n}
\end{pmatrix}$$

Where $\gamma_{i,j;k,l}(t) = Pr(C_{b;t+1} = k, C_{s;t+1} = l | C_{b;t} = i, C_{s;t} = j)$ is defined as the probability of volume bucket $t+1$ being in the state $(k,l)$ given that at bucket $t$ was in state $(i,j)$. 

The likelihood $L_T$ for the bivariate independent Poisson HMM is then formulated in exactly the same way as for the basic model \eqref{eq:likelihood} by calculating recursively using the forward probabilities $\boldsymbol{\alpha_t}$:

$$L_T = \boldsymbol{\delta} \mathbf{P}(x_1) \boldsymbol{\Gamma} \mathbf{P}(x_2) \dots   \boldsymbol{\Gamma} \mathbf{P}(x_T) \mathbf{1'}$$

#Estimation via EM

By examining the original CDDL equation we introduced in \eqref{eq:cddl}, we can start to extend this for the bivariate Poisson case in order to estimate VPIN:

\begin{align}
  \begin{aligned}\nonumber
    \text{log} \Big ( Pr(\mathbf{x}^{(T)}, \mathbf{c}^{(T)}) \Big ) &  
    = \sum_{j=1}^m u_j(1) \text{log } \delta_j
    + \sum_{j=1}^m \sum_{k=1}^m \Bigg ( \sum_{t=2}^T v_{jk}(t)   \Bigg ) \text{log } \gamma_{jk} 
    + \sum_{j=1}^m \sum_{t=1}^T u_j(t) \text{log } p_j(x_t)
  \end{aligned}
\end{align}

First we extend the original indicator variables \marginnote{Confusingly, @zucchini re-use the notation $u_j$ which has already been used to denote the unconditional state distribution}:

\begin{align}
  \begin{aligned}\nonumber
    u_{i,j}(t) & = 1 \iff C_{b;t} = i \text{ and } C_{s;t} = j\\
    v_{i,j;k,l}(t) & = 1 \iff C_{b;t-1} = i \text{ , }  C_{s;t-1} = i \text{ , }  C_{b;t} = k \text{ , } \text{ and }  C_{s;t} = l
  \end{aligned}
\end{align}

To give us the following CDDL:

\begin{align}
  \begin{aligned}\label{eq:cddlVPIN}
    \text{log} \Big ( Pr(\mathbf{x}^{(T)}, \mathbf{c}^{(T)}) \Big ) &  
    = \sum_{i=1}^m \sum_{j=1}^n u_{i,j}(1) \text{log } \delta_{i,j}
    + \sum_{i,k=1}^m \sum_{j,l=1}^n \Bigg ( \sum_{t=2}^T v_{i,j;k,l}(t)   \Bigg ) \text{log } \gamma_{i,j;k,l}(t) 
    + \sum_{i=1}^m \sum_{j=1}^n \sum_{t=1}^T u_{i,j}(t) \text{log } p_{i,j}(x_t)
  \end{aligned}
\end{align}

## E Step

Again, following the univariate examples \eqref{eq:uHat} and \eqref{eq:vHat} we find that the conditional expectations of the missing data given the observations are as follows:

\begin{align}
  \begin{aligned}\nonumber
    \hat{u}_{i,j}(t)  & = Pr(C_{b;t}=i,C_{s;t}=j| \mathbf{x}^{(T)}) \\
                      & = \alpha_t(i,j) \beta_{t}(i,j) / L_T
  \end{aligned}
\end{align}

\begin{align}
  \begin{aligned}\nonumber
    \hat{v}_{i,j;k,l}(t) & = Pr(C_{b;t-1}=i, C_{s;t-1}=j, C_{b;t}=k, C_{s;t}=l | \mathbf{x}^{(T)}) \\
                         & = \alpha_{t-1}(i,j) \gamma_{i,j;k,l} p_{k,l}(x_t) \beta_{t}(k,l) / L_T 
  \end{aligned}
\end{align}

## M Step

On completing the E step is complete, we now maximise the CDDL \eqref{eq:cddlVPIN} with respect to the four sets of parameters, $\boldsymbol{\delta}$, $\boldsymbol{\Gamma}$, $\lambda_{b;i}$ and $\lambda_{s;j}$. The state dependent distribution $p_{i,j}(x_t)$ as stated here \eqref{eq:bivarPois} is the independent bivariate Poisson distribution:  $e^{- \lambda_{b;i}} \frac{(\lambda_{b;i})^{b_t}}{b_t !} e^{- \lambda_{s;j}} \frac{(\lambda_{s;j})^{s_t}}{s_t !}$ \marginnote{For proof of this maximisation see appendix TODO}

\begin{align}
  \begin{aligned}\nonumber
    \text{Term to maximise} & \qquad \text{Parameter} & \text{Solution} \\
    \sum_{i=1}^m \sum_{j=1}^n u_{i,j}(1) \text{log } \delta_{i,j}                                             &\qquad \boldsymbol{\delta} & \delta_{i,j} = \frac{\hat{u}_{i,j}(1)}{ \sum_{i=1}^m \sum_{j=1}^n \hat{u}_{i,j}(1)} = \hat{u}_{i,j}(1)\\
    \sum_{i,k=1}^m \sum_{j,l=1}^n \Bigg ( \sum_{t=2}^T v_{i,j;k,l}(t) \Bigg ) \text{log } \gamma_{i,j;k,l}(t) &\qquad \boldsymbol{\Gamma} & \gamma_{i,j;k,l} = \frac{\sum_{t=2}^T \hat{v}_{i,j;k,l}(t)}{\sum_{k'=1}^m \sum_{l'=1}^n \sum_{t=2}^T \hat{v}_{i,j;k',l'}(t)} \\
    \sum_{i=1}^m \sum_{j=1}^n \sum_{t=1}^T u_{i,j}(t) \text{log } p_{i,j}(x_t)  & \qquad \lambda_{b;i}        &\hat{\lambda}_{b;i} = \frac{\sum_{i=1}^m \sum_{t=1}^T \hat{u}_i(t) b_t}{\sum_{t=1}^T \hat{u}_i(t)} \\
                                                                                & \qquad \lambda_{s;j}        &\hat{\lambda}_{s;j} = \frac{\sum_{j=1}^n \sum_{t=1}^T \hat{u}_j(t) s_t}{\sum_{t=1}^T \hat{u}_j(t)}
  \end{aligned}
\end{align}



#Estimation of Trading Motives via K-Means Clustering