---
title: “A Hidden Markov Model Approach to Evaluating VPIN”
header-includes:
   - \usepackage[]{algpseudocode}
   - \usepackage[]{verbatim}
bibliography: library.bib
csl: harvard1.csl
---
```{r setup,echo=FALSE,message=FALSE,cache=FALSE,include=TRUE,warning=FALSE}
# Its a good idea to start any rmarkdown document with a block like this one to set knit defaults, setup the bibliography, and so forth.
library(knitr)
library(xtable)
library(ggplot2)
library(pander)
options(xtable.comment = FALSE)
options(xtable.booktabs = TRUE)
options(digits = 3)

# This is also a good place to setup any ggplot2 themes for the document using ggplot2::theme_set()
```
\clearpage

```{r child = 'Preamble.Rmd'}
```
\clearpage

```{r child = 'Chapter 1.Rmd'}
```
\newpage
```{r child = 'Chapter 2.Rmd'}
```
\newpage
```{r child = 'Chapter 3.Rmd'}
```
\newpage
```{r child = 'Chapter 4.Rmd'}
```
\newpage
```{r child = 'Chapter 5.Rmd'}
```
\newpage
```{r child = 'Chapter 6.Rmd'}
```
\newpage
```{r child = 'Appendix 1.Rmd'}
```
\newpage
```{r child = 'Appendix 2.Rmd'}
```
\newpage
```{r child = 'Appendix 3.Rmd'}
```
\newpage
```{r child = 'References.Rmd'}
```
\newpage
